In [1]:
import numpy as np

## ndim shape size 

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.shape

(10,)

In [5]:
a.size

10

In [6]:
a.ndim

1

In [8]:
A = np.ones(shape = (2, 3))

In [9]:
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
A.ndim

2

In [11]:
A.shape

(2, 3)

In [12]:
A.size

6

In [13]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

In [14]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
X.ndim

2

In [16]:
X.shape

(2, 3)

In [17]:
X.size

6

In [18]:
X2 = np.array([[1, 2, 3],
               [4, 5]])

In [19]:
X2

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [20]:
X2.ndim

1

In [21]:
X2.shape

(2,)

In [23]:
X2.size    # 不是5

2

## reshape

In [25]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
s = a.reshape(2, 5)
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
a      # reshape并不会改变原来的数组维度

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
s.ndim

2

In [32]:
s.shape

(2, 5)

In [33]:
a.reshape(2, -1)      # 填 -1 numpy会自动算出需要变为多少列或多少行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
a.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
a.reshape(-1, 3)      # 可以让numpy自动算行或列，但一定要保证能够成功换算，否则会报错

ValueError: cannot reshape array of size 10 into shape (3)

 ## 取值

In [36]:
m = np.arange(15).reshape(3, 5)

In [37]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
m[0]

array([0, 1, 2, 3, 4])

In [40]:
m[-1]

array([10, 11, 12, 13, 14])

In [41]:
m[0][1]

1

In [42]:
m[(0, 1)]

1

In [43]:
m[0, 1]   # 一般采用这种方式

1

## 切片

In [44]:
b = np.arange(10)

In [45]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b[0:5]

array([0, 1, 2, 3, 4])

In [47]:
b[:5]

array([0, 1, 2, 3, 4])

In [48]:
b[5:]

array([5, 6, 7, 8, 9])

In [49]:
b[0:8:2]

array([0, 2, 4, 6])

In [50]:
b[::2]

array([0, 2, 4, 6, 8])

In [51]:
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组切片

In [53]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
m[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [55]:
m[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [57]:
m[:2][:3]   # 等效于 X2=m[:2]  X2[:3]  即先切出[0:2],再在前一次的结果上，再做[0:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
m[::2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [60]:
m[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

## 引用关系

### 1. python list中的引用关系

In [61]:
a = list(range(10))

In [62]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
b = a[:2]

In [64]:
b

[0, 1]

In [65]:
b[1] = 99
b

[0, 99]

In [66]:
a     # b引用a，b的值改变不影响a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 2. numpy.ndarray中的引用关系

In [67]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
type(m)

numpy.ndarray

In [70]:
m2 = m[:2, :2]

In [71]:
m2

array([[0, 1],
       [5, 6]])

In [72]:
m2[0, 0] = 99

In [73]:
m2

array([[99,  1],
       [ 5,  6]])

In [75]:
m       # numpy中为了提高效率，并没有在内存中拷贝一份，m2的值改变，m的值也就改变了

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [76]:
m3 = m[:3, :3].copy()
m3

array([[99,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [77]:
m3[0, 0] = 100
m3

array([[100,   1,   2],
       [  5,   6,   7],
       [ 10,  11,  12]])

In [78]:
m    # 切片时使用copy()函数，将拷贝一份出来

array([[99,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])