# numpy的综合运用

In [1]:
import numpy as np

In [2]:
np.random.seed(1)
X = np.random.randint(1, 10, size=30)

In [3]:
X

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

In [4]:
y = X.reshape(-1, 3)

In [5]:
y

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [6]:
y[0,-1]=6
y[0,-1]
y

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [7]:
y[:, -1]    # 获取最后一列数据

array([6, 2, 3, 3, 5, 2, 7, 2, 9, 9])

In [8]:
row = y[:, -1]<=3
row

array([False,  True,  True,  True, False,  True, False,  True, False,
       False])

In [9]:
# 将最后一列小于等于3的修改为0
lower_3 = [i for i in range(len(row)) if row[i]==True]
lower_3
for i in lower_3:
    y[i,-1] = 0
y

array([[6, 9, 6],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 5],
       [8, 8, 0],
       [8, 1, 7],
       [8, 7, 0],
       [1, 2, 9],
       [9, 4, 9]])

In [10]:
row2 = (y[:,-1]>3) & (y[:,-1]<=6)
row2

array([ True, False, False, False,  True, False, False, False, False,
       False])

In [11]:
# 将最后一列大于3小于等于6的修改为0
three_to_six = [i for i in range(len(row2)) if row2[i]==True]
three_to_six
for i in three_to_six:
    y[i,-1] = 1
y

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 7],
       [8, 7, 0],
       [1, 2, 9],
       [9, 4, 9]])

In [12]:
row3 = y[:, -1]>6
row3

array([False, False, False, False, False, False,  True, False,  True,
        True])

In [13]:
# 将最后一列大于6的修改为0
higher_six = [i for i in range(len(row3)) if row3[i]==True]
higher_six
for i in higher_six:
    y[i,-1] = 2
y

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])

In [14]:
X_train = y[:,0:2]
X_train

array([[6, 9],
       [1, 1],
       [8, 7],
       [5, 6],
       [5, 3],
       [8, 8],
       [8, 1],
       [8, 7],
       [1, 2],
       [9, 4]])

In [15]:
y_train = y[:,-1]
y_train

array([1, 0, 0, 0, 1, 0, 2, 0, 2, 2])

In [16]:
# 分类为0的样本
select1 = [ i for i in range(len(y_train)) if y_train[i]==0 ]
X1 = X_train[select1]
X1

array([[1, 1],
       [8, 7],
       [5, 6],
       [8, 8],
       [8, 7]])

In [17]:
# 分类为1的样本
select2 = [ i for i in range(len(y_train)) if y_train[i]==1 ]
X2 = X_train[select2]
X2

array([[6, 9],
       [5, 3]])

In [18]:
# 分类为2的样本
select3 = [ i for i in range(len(y_train)) if y_train[i]==2 ]
X3 = X_train[select3]
X3

array([[8, 1],
       [1, 2],
       [9, 4]])